# Generated by Django 3.1.7 on 2021-03-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_student_experience',
            new_name='student_experience',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_student_workload',
            new_name='student_workload',
        ),
    ]
