# Generated by Django 3.1.7 on 2021-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prereqs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Music', 'Music'), ('Computer Science', 'Computer Science'), ('Art', 'Art')], default='Math', max_length=100),
        ),
    ]
